apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brodin-nl
  namespace: traefik
spec:
  secretName: brodin-nl-tls
  issuerRef:
    name: lets-encrypt-issuer
    kind: ClusterIssuer
  commonName: "*.brodin.nl"
  dnsNames:
  - "*.brodin.nl"