

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

  - --certificatesresolvers.digitalocean.acme.dnschallenge.provider=digitalocean
  - --certificatesresolvers.digitalocean.acme.email=thijs@hejonet.nl
  - --certificatesresolvers.digitalocean.acme.storage=/ssl-certs/acme-digitalocean.json

env:
  - name: DO_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: digitalocean-credentials

# Incoming trafic into treafic
ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
      certResolver: digitalocean

# Disable dashboard
ingressRoute:
  dashboard:
    enabled: false

# Persistent Storage
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

# General deployment properties
deployment:
  initContainers:
    # The "volume-permissions" init container is required if you run into permission issues.
    # Related issue: https://github.com/containous/traefik/issues/6972
    - name: volume-permissions
      image: busybox:1.36.1
      command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/*"]
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

ingressClass:
  enabled: true
  isDefaultClass: true