# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: minecraft-data-pvc
#   namespace: minecraft-vanilla
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
